classdef BlackJackUI < handle
    %This class holds all of the UI elements for BlackJack.
    
    properties
        Figure
        VisualPanel
        InteractivePanel
        VisualAxes
        NameTexts %1-4
        FundTexts %1-4
        CheckBoxes %1-4
        BetBoxes %1-4
        RemoveButtons %1-4
        ResultTexts %1-4
        NameTexts2 %1-4
        NextButton
        LeaveButton
        RulesButton
        ActionButtons
        Title1
        Title2
        Title3
        HandStringPanel
        ValueString
        AddMenu
        AddButton
        HandDispPanels %1-9
        ResultDispAxes %1-9
        HandShowPanel
        DeckPanel
        DeckAxes
        DealerButton
        DealerD
        RulesFigure
        RulesPanel
        RulesAxes
        RulesText
        RulesLeaveButton
        
    end
    
    methods
        function obj = BlackJackUI(casino)
            obj.Figure = casino.Figure;
            obj.VisualPanel = uipanel('Parent',obj.Figure,...
                'Units','normalized',...
                'Position',[0 0.4 1 0.6],...
                'Visible','on');
            obj.InteractivePanel = uipanel('Parent',obj.Figure,...
                'Units','normalized',...
                'Position',[0 0 1 0.4],...
                'Visible','on');
            obj.VisualAxes = axes('Parent',obj.VisualPanel,...
                'Visible','on',...
                'Units','normalized',...
                'Position',[0 0 1 1]);
            
            imshow('visualBackground.jpeg','Parent',obj.VisualAxes);
            axis normal
            
            
            
            for i = 1:4
                obj.NameTexts{i} = uicontrol('Parent',obj.InteractivePanel,...   %TextName: variable position and string
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','text',...
                    'String',['Name' num2str(i)],...
                    'FontSize',15);
                obj.FundTexts{i} = uicontrol('Parent',obj.InteractivePanel,...   %TextFunds: variable position and string
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','text',...
                    'String',['Fund' num2str(i)],...
                    'FontSize',15);
                obj.CheckBoxes{i} = uicontrol('Parent',obj.InteractivePanel,...     %CheckBox: variable position and callback
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','checkbox');
                obj.BetBoxes{i} = uicontrol('Parent',obj.InteractivePanel,...   %BetBox: variable position and style
                    'Units','normalized',...
                    'Visible','off',...
                    'Style', 'edit',...
                    'String', 'default',...
                    'FontSize',15);
            end
            obj.NextButton = uicontrol('Parent',obj.InteractivePanel,...   %NextButton: variable position, string, and callback
                'Units','normalized',...
                'Visible','off',...
                'Style','pushbutton',...
                'String','default',...
                'FontSize',15);
            obj.LeaveButton = uicontrol('Parent',obj.InteractivePanel,...     %LeaveButton: variable position and callback
                'Units','normalized',...
                'Visible','off',...
                'String', 'Back to Casino',...
                'FontSize',15,...
                'Style','pushbutton');
            obj.RulesButton = uicontrol('Parent',obj.InteractivePanel,...  %RulesButton: variable position and callback
                'Units','normalized',...
                'Visible','off',...
                'Style','pushbutton',...
                'String', 'Table Rules',...
                'FontSize',15);
            actions = {'Hit','Split','Double','Surrender','Stay'};
            for i = 1:5
                obj.ActionButtons{i} = uicontrol('Parent',obj.InteractivePanel,...   %ActionButton: variable position and callback
                    'Units','normalized',...
                    'Visible','off',...
                    'String',actions{i},...
                    'Style','pushbutton',...
                    'FontSize',15);
            end
            obj.Title1 = uicontrol('Parent',obj.InteractivePanel,...  %Title1: variable position and string
                'Units','normalized',...
                'Visible','off',...
                'Style','text',...
                'String','default',...
                'FontSize',15);
            obj.Title2 = uicontrol('Parent',obj.InteractivePanel,...  %Title2: variable position and string
                'Units','normalized',...
                'Visible','off',...
                'Style','text',...
                'String','default',...
                'FontSize',15);
            obj.Title3 = uicontrol('Parent',obj.InteractivePanel,... %Title3: variable position and string
                'Units','normalized',...
                'Visible','off',...
                'Style','text',...
                'String','default',...
                'FontSize',15);
            obj.HandStringPanel = uipanel('Parent',obj.InteractivePanel,...  %HandStringPanel
                'Units','normalized',...
                'Visible','off',...
                'BorderType','none',...
                'Position',[0.505 0.6 0.45 0.1]);
            obj.ValueString = uicontrol('Parent',obj.InteractivePanel,...  %ValueString: variable position and string
                'Units','normalized',...
                'Visible','off',...
                'Style','text',...
                'String','default',...
                'FontSize',15,...
                'Position', [0.5 0.5 0.4 0.1]);
            obj.AddMenu = uicontrol('Parent',obj.InteractivePanel,...    %AddMenu: variable position and string
                'Units','normalized',...
                'Style','popupmenu',...
                'String','Error',...
                'Visible','off',...
                'FontSize',15);
            obj.AddButton = uicontrol('Parent',obj.InteractivePanel,...  %AddButton: variable position, string, and callback
                'Units','normalized',...
                'Visible','off',...
                'Style','pushbutton',...
                'String','default',...
                'FontSize',15);
            for i = 1:4
                obj.RemoveButtons{i} = uicontrol('Parent',obj.InteractivePanel,...    %RemoveButton: variable position and callback
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','pushbutton',...
                    'String','X',...
                    'FontSize',15);
            end
            size = get(obj.VisualPanel,'Position');
            w = size(3);
            h = size(4);
            w2 = 0.2*w;
            w1 = w2/5;
            h1 = 3775/2646*w1;
            h2 = 2*h1;
            
            
            
            
            obj.HandDispPanels{1} = uipanel('Parent',obj.VisualPanel,...          %HandDispPanel: all preset (except visibility)
                'Units','normalized',...
                'Visible','off',...
                'BorderType','none',...
                'BackgroundColor',[0 0 0],...
                'Position',[0.4 0.66 w2/w h2/h*w/h],...
                'HighlightColor',[1 0 0],...
                'BorderWidth',5);
            
            for i = 2:9
                if round(i/2) == i/2
                    obj.HandDispPanels{i} = uipanel('Parent',obj.VisualPanel,...
                        'Units','normalized',...
                        'Visible','off',...
                        'BorderType','none',...
                        'BackgroundColor',[0 0 0],...
                        'Position',[(1-4*w2/w)/5+(i/2-1)*(w2/w+(1-4*w2/w)/5) 0.01 w2/w h2/h*w/h],...
                        'HighlightColor',[1 0 0],...
                        'BorderWidth',5);
                else
                    obj.HandDispPanels{i} = uipanel('Parent',obj.VisualPanel,...
                        'Visible','off',...
                        'Units','normalized',...
                        'BorderType','none',...
                        'BackgroundColor',[0 0 0],...
                        'Position',[(1-4*w2/w)/5+((i-1)/2-1)*(w2/w+(1-4*w2/w)/5) 0.34 w2/w h2/h*w/h],...
                        'HighlightColor',[1 0 0],...
                        'BorderWidth',5);
                end
            end
            for i = 1:9
                obj.ResultDispAxes{i} = axes('Parent',obj.HandDispPanels{i},...
                    'Units','normalized',...
                    'Visible','off');
            end
            obj.HandShowPanel = uipanel('Parent',obj.InteractivePanel,...
                'Units','normalized',...
                'Visible','off',...
                'Position',[0.4 0.6 0.1 0.25]);
            
            for i = 1:4
                obj.ResultTexts{i} = uicontrol('Parent',obj.InteractivePanel,...
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','text',...
                    'String','default',...
                    'FontSize',15);
                obj.NameTexts2{i} = uicontrol('Parent',obj.VisualPanel,...
                    'Units','normalized',...
                    'Visible','off',...
                    'Style','text',...
                    'String','default',...
                    'FontSize',15);
            end
            obj.DeckPanel = uipanel('Parent',obj.VisualPanel,...
                'Units','normalized',...
                'Visible','off',...
                'Position',[0.1 0.67 0.08 h2/h*w/h],...
                'BorderType','none');
            obj.DeckAxes = axes('Parent',obj.DeckPanel,...
                'Units','normalized',...
                'Visible','on',...
                'Position',[0 0 1 1]);
            obj.DealerButton = axes('Parent',obj.VisualPanel,...
                'Units','normalized',...
                'Visible','off',...
                'Position',[0.31 0.66 0.10 0.10*w/h]);
            obj.DealerD = uicontrol('Parent',obj.VisualPanel,...
                'Units','normalized',...
                'Style','text',...
                'Visible','off',...
                'Position',[0.345 0.705 0.03 0.08],...
                'String','D',...
                'FontSize',25,...
                'BackgroundColor',[0 0 0],...
                'ForegroundColor',[1 1 1]);
            obj.RulesFigure = figure('Visible','off',...
                'Units','normalized',...
                'Position',[0.35 0.1 0.3 0.4],...
                'CloseRequestFcn',@(h,d) dontclose,...
                'Toolbar','none',...
                'Name','Table Rules',...
                'DockControls','off',...
                'MenuBar','none',...
                'NumberTitle','off');
            function dontclose(h,d)
                %don't close
            end
            obj.RulesPanel = uipanel('Parent',obj.RulesFigure,...
                'Units','normalized',...
                'Visible','on',...
                'Position', [0 0 1 1]);
            obj.RulesAxes = axes('Parent',obj.RulesPanel,...
                'Units','normalized',...
                'Visible','on',...
                'Position',[0 0 1 1]);
            imshow('visualBackground.jpeg','Parent',obj.RulesAxes);
            axis normal
            obj.RulesText = uicontrol('Parent',obj.RulesPanel,...
                'Units','normalized',...
                'Visible','on',...
                'Position',[0.1 0.35 0.8 0.55],...
                'Style','text',...
                'BackgroundColor',[0 0 0],...
                'ForegroundColor',[1 1 1],...
                'String',{'' 'Table Rules:' '' 'Dealer Stands on all 17s.' 'Insurance Pays 2 to 1.' 'BlackJack Pays 3 to 2.'},...
                'FontSize',15);
            obj.RulesLeaveButton = uicontrol('Parent',obj.RulesPanel,...
                'Units','normalized',...
                'Visible','on',...
                'Style','pushbutton',...
                'String','Resume Game',...
                'FontSize',15,...
                'Position',[0.2 0.1 0.6 0.13],...
                'CallBack', @(h,d) rulesleave_callback);
            function rulesleave_callback(h,d)
                set(obj.RulesFigure,'Visible','off');
            end
        end
        
        
    end
    
end

