classdef RouletteTable < handle
   % This Class is ued to create the Betting table for roulette.  It
   % provides the user interface that the user uses to choose which
   % locations and how much money they with to bet.
    
    properties
        Roulette  % Roulette class object
    end
    
    methods
        function obj = RouletteTable(rou)
            obj.Roulette = rou;
        end
        function disp(routable)  %displays the roulette betting table
            num = cell(38,1);
            col1 = []; col2 = []; odds = []; evens = []; doz1 = [];doz2 = [];
            doz3 = []; top = []; bot = []; colm1 = []; colm2 = []; colm3 = [];
            cols = {'r' 'k' 'r' 'k' 'r' 'k' 'r' 'k' 'r' 'k' 'k' 'r' 'k'...
                'r' 'k' 'r' 'k' 'r' 'k' 'k' 'r' 'k' 'r' 'k' 'r' 'k' 'r'...
                'r' 'k' 'k' 'k' 'r' 'k' 'r' 'k' 'r'};
            Betpanel = uipanel('Parent',routable.Roulette.Casino.Figure,... % the Bet panel
                'Units','normalized',...
                'Position',[.5 0 .5 1], ...
                'Backgroundcolor',get(routable.Roulette.Casino.Figure,'color'));
            Betaxes = axes('Parent',Betpanel,...      %bet Axes for the image
                'Visible','on',...
                'Units','normalized',...
                'Position',[0 0 1 1]);
            imshow('rouBackground.jpeg','Parent',Betaxes)
            BetButton = uicontrol('Parent',Betpanel,...% the finished button
                'Style','pushbutton',...
                'String','Done',...
                'FontSize',15,...
                'Units','normalized',...
                'Position',[.04 .45 .2 .1],...
                'TooltipString','Finished Placing bets?',...
                'Callback',@bet_callback);
            RulesButton = uicontrol('Parent',Betpanel,...% the table rules button
                'Style','pushbutton',...
                'String','Table Rules',...
                'FontSize',15,...
                'Units','normalized',...
                'Position',[.04 .25 .2 .1],...
                'TooltipString','Check the rules for this table.',...
                'Callback',@rules_callback);
            
            LeaveButton = uicontrol('Parent',routable.Roulette.Wheel.WheelPanel,...% the Leave button
                'Style','pushbutton',...
                'String', 'Leave Roulette.',...
                'FontSize',15,...
                'Units', 'normalized',...
                'Position',[.35 .03 .3 .05],...
                'Callback',@leave_callback);
            funds = routable.Roulette.Casino.CurrentPlayers{routable.Roulette.CurrentPlayer}.Funds;
            fundss = num2str(funds);
            sth1  = uicontrol('Parent',Betpanel,...
                'Style','text',...
                'Backgroundcolor',get(routable.Roulette.Casino.Figure,'color'),...
                'String',[routable.Roulette.Casino.CurrentPlayers{routable.Roulette.CurrentPlayer}.Name ' funds:  $' fundss],...
                'FontSize',15,...
                'Units','normalized',...
                'Position',[.2 .94 .6 .04]);
            sth2  = uicontrol('Parent',Betpanel,...
                'Style','text',...
                'Backgroundcolor',get(routable.Roulette.Casino.Figure,'color'),...
                'String','Where would you like to bet?',...
                'FontSize',15,...
                'Units','normalized',...
                'Position',[.2 .84 .6 .07]);
            pbh = cell(1,36);
            for k = 1:36
                locs = num2str(k);
                switch rem(k,3)
                    case 1
                        n = 1;
                    case 2
                        n = 2;
                    case 0
                        n = 3;
                end
                m = floor(k/3-.1);
                pbh{k}  = uicontrol('Parent',Betpanel,...  % The table of toggle buttons for betting 
                    'Style','togglebutton',...
                    'Backgroundcolor',cols{k},...
                    'Foregroundcolor','w',...
                    'String',locs ,...
                    'FontSize',15,...
                    'Units','normalized',...
                    'Callback',{@n_callback},...
                    'TooltipString','35 to 1',...
                    'Position',[.18+.1*n .70-.05*m .10 .05]);
            end
            
            % Toggle buttons for betting on green and outside bets.
            pbh0  = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'Backgroundcolor',[0 0.5020 0],...
                'Foregroundcolor','w',...
                'String','0',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@n_callback},...
                'TooltipString','35 to 1',...
                'Position',[.28 .75 .15 .05]);
            pbh00 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'Backgroundcolor',[0 0.5020 0],...
                'Foregroundcolor','w',...
                'String','00',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@n_callback},...
                'TooltipString','35 to 1',...
                'Position',[.43 .75 .15 .05]);
            
            pbhcol1 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','2 to 1',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@col1_callback},...
                'TooltipString','First Column',...
                'Position',[.28 .10 .10 .05]);
            pbhcol2 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','2 to 1',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@col2_callback},...
                'TooltipString','Second Column',...
                'Position',[.38 .10 .10 .05]);
            pbhcol3 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','2 to 1',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@col3_callback},...
                'TooltipString','Third Column',...
                'Position',[.48 .10 .10 .05]);
            
            pbhdoz1 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','1-12',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@doz1_callback},...
                'TooltipString','2 to 1',...
                'Position',[.58 .55 .10 .2]);
            pbhdoz2 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','13-24',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@doz2_callback},...
                'TooltipString','2 to 1',...
                'Position',[.58 .35 .10 .2]);
            pbhdoz3 = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','25-36',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@doz3_callback},...
                'TooltipString','2 to 1',...
                'Position',[.58 .15 .10 .2]);
            
            pbhodd = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','odd',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@odd_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .25 .10 .1]);
            pbheven = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','even',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@even_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .55 .10 .1]);
            
            pbhtop = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','1-18',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@top_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .65 .10 .1]);
            pbhbot = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'String','19-36',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@bot_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .15 .10 .1]);
            
            pbhblack = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'Backgroundcolor','k',...
                'Foregroundcolor','w',...
                'String','black',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@black_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .35 .10 .1]);
            pbhred = uicontrol('Parent',Betpanel,...
                'Style','togglebutton',...
                'Backgroundcolor','r',...
                'Foregroundcolor','w',...
                'String','red',...
                'FontSize',15,...
                'Units','normalized',...
                'Callback',{@red_callback},...
                'TooltipString','1 to 1',...
                'Position',[.68 .45 .10 .1]);
            % Call backs for all buttons created above
            function red_callback(pbhred,eventdata)
                button_state = get(pbhred,'Value');
                if button_state == get(pbhred,'Max')
                    col1 = 'Red';
                else
                    col1 = [];
                end
            end
            function black_callback(pbhblack,eventdata)
                button_state = get(pbhblack,'Value');
                if button_state == get(pbhblack,'Max')
                    col2 = 'Black';
                else
                    col2 = [];
                end
            end
            
            function odd_callback(pbhodd,eventdata)
                button_state = get(pbhodd,'Value');
                if button_state == get(pbhodd,'Max')
                    odds = 'Odd';
                else
                    odds = [];
                end
            end
            function even_callback(pbheven,eventdata)
                button_state = get(pbheven,'Value');
                if button_state == get(pbheven,'Max')
                    evens = 'Even';
                else
                    evens = [];
                end
            end
            
            function top_callback(pbhtop,eventdata)
                button_state = get(pbhtop,'Value');
                if button_state == get(pbhtop,'Max')
                    top = '1-18';
                else
                    top = [];
                end
            end
            function bot_callback(pbhbot,eventdata)
                button_state = get(pbhbot,'Value');
                if button_state == get(pbhbot,'Max')
                    bot = '19-36';
                else
                    bot = [];
                end
            end
            
            function doz1_callback(pbhdoz1,eventdata)
                button_state = get(pbhdoz1,'Value');
                if button_state == get(pbhdoz1,'Max')
                    doz1 = '1-12';
                else
                    doz1 = [];
                end
            end
            function doz2_callback(pbhdoz2,eventdata)
                button_state = get(pbhdoz2,'Value');
                if button_state == get(pbhdoz2,'Max')
                    doz2 = '13-24';
                else
                    doz2 = [];
                end
            end
            function doz3_callback(pbhdoz3,eventdata)
                button_state = get(pbhdoz3,'Value');
                if button_state == get(pbhdoz3,'Max')
                    doz3 = '25-36';
                else
                    doz3 = [];
                end
            end
            
            function col1_callback(pbhcol1,eventdata)
                button_state = get(pbhcol1,'Value');
                if button_state == get(pbhcol1,'Max')
                    colm1 = 'Column1';
                else
                    colm1 = [];
                end
            end
            function col2_callback(pbhcol2,eventdata)
                button_state = get(pbhcol2,'Value');
                if button_state == get(pbhcol2,'Max')
                    colm2 = 'Column2';
                else
                    colm2 = [];
                end
            end
            function col3_callback(pbhcol3,eventdata)
                button_state = get(pbhcol3,'Value');
                if button_state == get(pbhcol3,'Max')
                    colm3 = 'Column3';
                else
                    colm3 = [];
                end
            end
            
            function n_callback(pbh,eventdata)
                button_state = get(pbh,'Value');
                numss = get(pbh,'String');
                numi = str2double(numss);
                switch numss
                    case '00'
                        numi = 38;
                    case '0'
                        numi = 37;
                end
                if button_state == get(pbh,'Max')
                    num{numi} = numss;
                else
                    num{numi} = [];
                end
            end
            function bet_callback(hObject,eventdata)
                j = [];
                for i = 1:length(num)
                    if ~isempty(num{i})
                        j = 1;
                        break
                    end
                end
                if isempty(j) && isempty([col1 col2 evens odds doz1 doz2 doz3 top bot colm1 colm2 colm3])
                    h = errordlg('Must have at least one bet!','Error','modal');
                else
                    set(Betpanel,'Visible','off')
                    set(LeaveButton,'Visible','off')
                    drawnow
                    routable.PlaceBet(num,evens,odds,col1,col2,doz1,doz2,doz3,top,bot,colm1,colm2,colm3)
                end
            end
            function leave_callback(hObject,eventdata)
                set(Betpanel,'Visible','off')
                set(routable.Roulette.Wheel.WheelPanel,'Visible','off')
                set(routable.Roulette.Wheel.BackPanel,'Visible','off')
                drawnow
                routable.Roulette.Casino.ChooseGame
            end
            function rules_callback(hObject,eventdata)
                routable.TableRules
            end
        end
    end
    
end